### ISSUE TITLE
Automated Pull returns parsing error

### ISSUE THREAD

**Issue by oskasf** [daaronr/fundraising_data_pull#1]
I have managed to use the scheduleR package in order to get the code running, however, I am encountering an issue when the code is executed which halts the running of main_automated.R. 
Automating the running of the following code (which exists in both just_giving_data_pull.R and just_giving_data_pull_sample.R: 
`#Get all fundraisers for target charities (just basic information)
fundraiser_search_data <-
  map2(charity_data$charity_name, charity_data$justgiving_id, get_charity_fundraising_pages) %>%
  reduce(bind_rows) `
returns the following error:
` Error in content(., as = "parsed") : unused argument (as = "parsed") `

Any thoughts on this @daaronr ?

**Comment by daaronr** [comment]
I'm not sure.
-  It might be that one of the functions used within `reduce` or in `map2` has changed with a new update 
- which part of the chain throws the error? 
- try digging into these functions' components
- look up this error on Google/stackexchange
- if you can't find an answer post a MWE using a built in dataset on Stackexchange
